Repository etalab/catalogage-donnees, pull requests merged in 2022-01, with the labels that each got.

#30 Add staging Ansible setup
  .gitignore
  Makefile
  docs/fr/ops.md
  ops/Makefile
  ops/ansible/ansible.cfg
  ops/ansible/hosts_staging
  ops/ansible/playbook.yml
  ops/ansible/roles/common/handlers/main.yml
  ops/ansible/roles/common/tasks/main.yml
  ops/ansible/roles/pyenv/README.md
  ops/ansible/roles/pyenv/defaults/main.yml
  ops/ansible/roles/pyenv/tasks/global_version.yml
  ops/ansible/roles/pyenv/tasks/install.yml
  ops/ansible/roles/pyenv/tasks/main.yml
  ops/ansible/roles/pyenv/tasks/python.yml
  ops/ansible/roles/pyenv/tasks/setup.yml
  ops/ansible/roles/pyenv/tasks/shell.yml
  ops/ansible/roles/pyenv/templates/.pyenvrc.j2
  ops/ansible/roles/web/tasks/db.yml
  ops/ansible/roles/web/tasks/env.yml
  ops/ansible/roles/web/tasks/git.yml
  ops/ansible/roles/web/tasks/main.yml
  ops/ansible/roles/web/tasks/nginx.yml
  ops/ansible/roles/web/tasks/python.yml
  ops/ansible/roles/web/tasks/supervisor.yml
  ops/ansible/roles/web/templates/nginx.conf.j2
  ops/ansible/roles/web/templates/supervisor.conf.j2
  ops/ansible/secrets/staging.enc
  requirements.txt
  server/migrations/env.py
Labels: tooling, ops, need-review

#36 Add CORS for local dev
  server/api/app.py
  tests/test_app.py
Labels: technical

#27 Update dataset API with title/description fields
  server/api/datasets/routes.py
  server/api/datasets/schemas.py
  server/application/datasets/commands.py
  server/application/datasets/handlers.py
  server/domain/datasets/entities.py
  server/infrastructure/datasets/repositories.py
  server/migrations/versions/f050fa78b42c_update_dataset_title_description.py
  tests/api/test_datasets.py
  tests/domain/test_datasets.py
Labels: need-review
