Repository etalab/catalogage-donnees, pull requests merged in 2022-10, with the labels that each got.

#458 Create prod environment and extra tooling
  Makefile
  docs/fr/ops.md
  ops/ansible/environments/prod/group_vars/web.yml
  ops/ansible/environments/prod/hosts
  ops/ansible/environments/prod/secrets
  tests/tools/test_apikey.py
  tests/tools/test_secretkey.py
  tools/makeapikey.py
  tools/makesecretkey.py
Labels: infra

#463 Fix missing organization_siret in datapass login params payload
  client/src/lib/repositories/auth.ts
  client/src/tests/e2e/constants.ts
  client/src/tests/e2e/datapass.spec.ts
  server/api/auth/datapass/routes.py
  tests/api/test_auth_datapass.py
Labels: bug, front, staging

#461 Increase Nginx proxy buffer sizes
  ops/ansible/roles/web/templates/nginx.conf.j2
Labels: infra, staging

#460 Configure admin account on prod
  ops/ansible/environments/prod/assets/initdata.yml
  ops/ansible/environments/prod/group_vars/web.yml
  ops/ansible/environments/prod/secrets
Labels: infra

#470 Fix logout from dataset detail page
  client/src/lib/permissions.ts
  client/src/routes/(app)/fiches/[id]/+page.svelte
  client/src/tests/e2e/details.spec.ts
Labels: bug, front

#478 Register DataPass client credentials on prod
  ops/ansible/environments/prod/secrets
Labels: infra

#471 Remove reliance on LEGACY_ORGANIZATION
  server/api/auth/routes.py
  server/api/auth/schemas.py
  server/api/datasets/schemas.py
  server/application/auth/commands.py
  server/application/auth/handlers.py
  server/application/datasets/commands.py
  server/domain/organizations/entities.py
  tests/api/test_auth.py
  tests/api/test_catalogs.py
  tests/api/test_datasets.py
  tests/api/test_datasets_filters.py
  tests/api/test_datasets_search.py
  tests/api/test_licenses.py
  tests/api/test_organizations.py
  tests/application/test_auth.py
  tests/conftest.py
  tests/factories.py
  tests/helpers.py
  tests/infrastructure/test_datasets.py
  tests/tools/test_addrandomdatasets.py
  tests/tools/test_initdata.py
Labels: refactor, back

#484 Add missing prod env to environment list
  docs/fr/README.md
  docs/fr/ops.md
Labels: docs

#485 Drop sandbox environment
  docs/fr/ops.md
  ops/ansible/environments/sandbox/group_vars/web.yml
  ops/ansible/environments/sandbox/hosts
  ops/ansible/environments/sandbox/secrets
  server/api/auth/permissions.py
Labels: infra

#489 Drop legacy org from catalog filter choices
  server/application/datasets/handlers.py
  tests/api/test_datasets_filters.py
  tests/helpers.py
Labels: minor fix

#491 Fix: Reuse any datapass user account when creating a password user
  server/application/auth/handlers.py
  tests/application/test_auth.py
Labels: bug, back

#475 Update common fields appearance in details page
  client/src/routes/(app)/fiches/[id]/+page.svelte
Labels: front, minor fix

#497 Set API docs title
  server/api/app.py
Labels: docs, back, minor fix

#516 HOTFIX: remove purgecss
  client/vite.config.js
Labels: technical, hotfix

#514 fix: should be able to close the form if no change has been made
  client/src/lib/components/DatasetForm/DatasetForm.svelte
  client/src/lib/components/ModalExitFormConfirmation/ModalExitFormConfirmation.svelte
  client/src/routes/(app)/fiches/[id]/edit/+page.svelte
Labels: bug, front, staging

#504 Add experimental import tool and documentation
  docs/fr/README.md
  docs/fr/outils-orgas.md
  setup.cfg
  tests/tools/test_import_catalog.py
  tools/import.config.example.yml
  tools/import_catalog.py
Labels: docs, technical

#521 fix: remove svelte's a11y warning
  client/package.json
  client/src/lib/components/DatasetForm/DatasetForm.svelte
  client/src/lib/components/Footer/Footer.svelte
  client/src/lib/components/GenericModal/GenericModal.svelte
  client/src/lib/components/Header/Header.svelte
  client/src/lib/components/Pagination/Pagination.svelte
  client/src/routes/(app)/+layout.svelte
Labels: front, a11y
