Repository etalab/catalogage-donnees, pull requests merged in 2022-08, with the labels that each got.

#363 Move UserModel to a models.py file
  server/infrastructure/auth/models.py
  server/infrastructure/auth/repositories.py
  server/infrastructure/auth/transformers.py
Labels: refactor, back

#366 Use pip cache in CI
  .github/workflows/ci.yml
Labels: technical

#364 Split User into Account and PasswordUser
  server/api/auth/backends/token.py
  server/api/auth/models.py
  server/api/auth/permissions.py
  server/api/auth/routes.py
  server/api/auth/schemas.py
  server/application/auth/commands.py
  server/application/auth/handlers.py
  server/application/auth/queries.py
  server/application/auth/views.py
  server/config/di.py
  server/domain/auth/entities.py
  server/domain/auth/exceptions.py
  server/domain/auth/repositories.py
  server/infrastructure/auth/models.py
  server/infrastructure/auth/module.py
  server/infrastructure/auth/repositories.py
  server/infrastructure/auth/transformers.py
  server/infrastructure/organizations/models.py
  server/migrations/versions/17a9b8d2f84e_split_account_password_user.py
  tests/api/test_auth.py
  tests/api/test_datasets.py
  tests/api/test_datasets_filters.py
  tests/api/test_datasets_search.py
  tests/api/test_licenses.py
  tests/api/test_organizations.py
  tests/api/test_tags.py
  tests/application/test_auth.py
  tests/conftest.py
  tests/factories.py
  tests/helpers.py
  tests/infrastructure/test_catalogs.py
  tests/tools/test_initdata.py
  tests/unit/test_permissions.py
  tools/changepassword.py
  tools/initdata.py
Labels: refactor, back

#369 Switch to chronologically listed revision files
  alembic.ini
  server/migrations/versions/2021-12-09_672a958cc788_create_dataset.py
  server/migrations/versions/2022-01-03_d24cec0c6ddd_add_user.py
  server/migrations/versions/2022-01-17_f050fa78b42c_update_dataset_title_description.py
  server/migrations/versions/2022-01-20_7b3e0dc2a28e_update_uuid.py
  server/migrations/versions/2022-02-16_1bef6a411f5c_dataset_add_formats.py
  server/migrations/versions/2022-02-22_cc869b534916_add_dataset_search_tsv.py
  server/migrations/versions/2022-03-01_30474ebed7a2_user_add_password_token.py
  server/migrations/versions/2022-03-16_26e723d032b1_dataset_add_created_at.py
  server/migrations/versions/2022-03-30_d694d065978d_add_dataset_entrypoint_email.py
  server/migrations/versions/2022-03-31_67a6c2bf0696_add_dataset_contact_emails.py
  server/migrations/versions/2022-04-05_6fd05f9d4158_add_dataset_service_update_frequency_last_updated_at.py
  server/migrations/versions/2022-04-07_1cbaaf0d013b_add_user_role.py
  server/migrations/versions/2022-04-14_e951f6fd7fbf_add_dataset_tags.py
  server/migrations/versions/2022-04-14_f92d0ee57d88_add_dataset_geographical_coverage_.py
  server/migrations/versions/2022-04-20_012e4606ddc1_add_catalog_record.py
  server/migrations/versions/2022-04-25_531a8496be5e_add_dataset_published_url.py
  server/migrations/versions/2022-05-02_ae61063248aa_update_entrypoint_email_contact_emails.py
  server/migrations/versions/2022-06-29_1cd8f59f2f0f_add_dataset_license.py
  server/migrations/versions/2022-07-06_b3dac4035ce9_rename_published_url_to_url.py
  server/migrations/versions/2022-07-11_663792a4c86c_update_geographical_coverage_string.py
  server/migrations/versions/2022-07-13_d9ea6ea6708f_add_organization.py
  server/migrations/versions/2022-07-19_4e40358ad25c_add_catalog.py
  server/migrations/versions/2022-07-19_da164fd0fa6f_swap_dataset_catalog_record_fk.py
  server/migrations/versions/2022-07-20_f2ef4eef61e3_create_legacy_organization.py
  server/migrations/versions/2022-08-02_17a9b8d2f84e_split_account_password_user.py
Labels: technical, refactor, back

#371 Add catalog creation endpoint
  server/api/catalogs/__init__.py
  server/api/catalogs/routes.py
  server/api/catalogs/schemas.py
  server/api/routes.py
  server/application/catalogs/__init__.py
  server/application/catalogs/commands.py
  server/application/catalogs/handlers.py
  server/application/catalogs/queries.py
  server/application/catalogs/views.py
  server/config/di.py
  server/domain/catalogs/exceptions.py
  server/domain/catalogs/repositories.py
  server/infrastructure/catalogs/module.py
  server/infrastructure/catalogs/repositories.py
  server/infrastructure/catalogs/transformers.py
  tests/api/test_catalogs.py
  tests/api/test_organizations.py
  tests/helpers.py
Labels: back

#365 Add DataPass auth backend integration
  .env.example
  .github/workflows/ci.yml
  docs/fr/demarrage.md
  docs/fr/ops.md
  ops/ansible/environments/demo/group_vars/web.yml
  ops/ansible/environments/demo/secrets
  ops/ansible/environments/sandbox/group_vars/web.yml
  ops/ansible/environments/sandbox/secrets
  ops/ansible/environments/staging/group_vars/web.yml
  ops/ansible/environments/staging/secrets
  ops/ansible/roles/web/templates/.env.j2
  requirements.txt
  server/api/app.py
  server/api/auth/datapass/__init__.py
  server/api/auth/datapass/routes.py
  server/api/auth/routes.py
  server/api/utils/urls.py
  server/application/auth/commands.py
  server/application/auth/handlers.py
  server/application/auth/queries.py
  server/config/di.py
  server/config/settings.py
  server/domain/auth/entities.py
  server/domain/auth/exceptions.py
  server/domain/auth/repositories.py
  server/domain/common/exceptions.py
  server/domain/organizations/repositories.py
  server/infrastructure/auth/datapass.py
  server/infrastructure/auth/models.py
  server/infrastructure/auth/module.py
  server/infrastructure/auth/repositories.py
  server/infrastructure/auth/transformers.py
  server/infrastructure/organizations/repositories.py
  server/migrations/versions/3928481ec7d2_add_datapass_user.py
  tests/api/test_auth_datapass.py
  tests/conftest.py
  tests/domain/organizations/test_types.py
Labels: back, staging

#374 Feat add organization and catalog fixtures in init data
  docs/db.png
  ops/ansible/environments/staging/assets/initdata.yml
  tests/tools/test_initdata.py
  tools/initdata.py
  tools/initdata.yml
Labels: back

#384 Fix cross link to Comptes DataPass extra info
  docs/fr/demarrage.md
Labels: docs

#381 feat: add catalog and organization fixtures for staging
  ops/ansible/environments/demo/assets/initdata.yml
  ops/ansible/environments/staging/assets/initdata.yml
  tools/initdata.yml
Labels: staging

#375 feat: display home page without beeing connected
  client/src/constants.ts
  client/src/lib/assets/books-circle.svg
  client/src/lib/assets/registration_flow_chart.svg
  client/src/lib/components/Header/Header.svelte
  client/src/lib/components/Spinner/Spinner.svelte
  client/src/lib/templates/DatasetListTemplate/DatasetListTemplate.svelte
  client/src/lib/templates/LandingTemplate/LandingTemplate.svelte
  client/src/lib/util/format.ts
  client/src/routes/index.svelte
  client/src/tests/e2e/home.spec.ts
  client/src/tests/e2e/login.spec.ts
Labels: staging

#386 Fix add_datapass_user migration file name
  server/migrations/versions/2022-08-03_3928481ec7d2_add_datapass_user.py
Labels: technical, refactor, back

#368 Add catalog extra fields backend
  ops/ansible/environments/demo/assets/initdata.yml
  ops/ansible/environments/staging/assets/initdata.yml
  server/api/catalogs/routes.py
  server/api/catalogs/schemas.py
  server/api/datasets/schemas.py
  server/application/catalogs/commands.py
  server/application/catalogs/handlers.py
  server/application/catalogs/validation.py
  server/application/catalogs/views.py
  server/application/datasets/commands.py
  server/application/datasets/handlers.py
  server/application/datasets/views.py
  server/domain/catalogs/entities.py
  server/domain/catalogs/repositories.py
  server/domain/datasets/entities.py
  server/infrastructure/catalogs/models.py
  server/infrastructure/catalogs/repositories.py
  server/infrastructure/catalogs/transformers.py
  server/infrastructure/datasets/models.py
  server/infrastructure/datasets/queries/get_all.py
  server/infrastructure/datasets/repositories.py
  server/infrastructure/datasets/transformers.py
  server/migrations/versions/2022-08-09_21a0f4491f8d_add_extra_fields.py
  tests/api/test_catalogs.py
  tests/api/test_datasets.py
  tests/factories.py
  tools/initdata.yml
Labels: back

#394 Fix DataPass login when account already exists via a PasswordUser
  server/application/auth/handlers.py
  server/domain/auth/repositories.py
  server/infrastructure/auth/repositories.py
  tests/api/test_auth_datapass.py
Labels: bug, back

#380 feat: Datapass only one organisation found
  client/src/constants.ts
  client/src/definitions/auth.ts
  client/src/lib/templates/LandingTemplate/LandingTemplate.svelte
  client/src/routes/auth/datapass/login.svelte
  client/src/tests/e2e/constants.ts
  client/src/tests/e2e/datapass.spec.ts
  client/src/tests/e2e/fixtures.ts
Labels: front, staging

#395 Add endpoint to register a DataPassUser
  requirements.txt
  server/api/auth/datapass/routes.py
  server/api/auth/datapass/schemas.py
  server/api/auth/permissions.py
  server/application/auth/passwords.py
  server/config/di.py
  server/infrastructure/auth/passwords.py
  tests/api/test_auth_datapass.py
  tests/factories.py
Labels: back

#397 Purge and minify CSS
  client/package-lock.json
  client/package.json
  client/svelte.config.js
  client/vite.config.js
Labels: front, perf

#398 Exclude home page from SSR to fix connected flash
  client/src/constants.ts
  client/src/hooks.ts
  client/src/lib/auth/guard.ts
Labels: front, perf
