Repository etalab/catalogage-donnees, pull requests merged in 2022-05, with the labels that each got.

#207 Allow running initdata on remote environments
  .gitignore
  Makefile
  docs/fr/ops.md
  docs/fr/outils.md
  ops/.gitignore
  ops/Makefile
  ops/ansible/environments/demo/assets/initdata.yml
  ops/ansible/environments/demo/group_vars/web.yml
  ops/ansible/environments/demo/secrets
  ops/ansible/environments/staging/assets/initdata.yml
  ops/ansible/environments/staging/group_vars/web.yml
  ops/ansible/environments/staging/secrets
  ops/ansible/roles/web/tasks/initdata.yml
  ops/ansible/roles/web/tasks/main.yml
  ops/ansible/roles/web/templates/.env.j2
  ops/run/.gitkeep
  tools/initdata.py
Labels: infra, technical, refactor

#204 Enable strict null checks
  client/src/definitions/auth.ts
  client/src/env.ts
  client/src/lib/auth/guard.ts
  client/src/lib/components/ContactEmailsField/ContactEmailsField.spec.ts
  client/src/lib/components/DatasetForm/DatasetForm.spec.ts
  client/src/lib/components/DatasetForm/DatasetForm.svelte
  client/src/lib/components/Header/Header.svelte
  client/src/lib/components/LoginForm/LoginForm.spec.ts
  client/src/lib/components/SearchForm/SearchForm.spec.ts
  client/src/lib/components/Select/Select.spec.ts
  client/src/lib/components/Select/Select.svelte
  client/src/lib/repositories/datasets.ts
  client/src/lib/stores/auth/index.ts
  client/src/lib/util/form.ts
  client/src/lib/util/maybe.ts
  client/src/lib/util/urls.spec.ts
  client/src/lib/util/urls.ts
  client/src/playwright.config.ts
  client/src/routes/__error.svelte
  client/src/routes/contribuer/index.svelte
  client/src/routes/fiches/[id]/edit.svelte
  client/src/routes/fiches/[id]/index.svelte
  client/src/routes/fiches/search.svelte
  client/src/routes/index.svelte
  client/src/tests/e2e/global-setup.ts
  client/tsconfig.json
Labels: refactor

#208 Front : rework contribution form to fit with the new ui
  client/package-lock.json
  client/src/lib/components/DatasetForm/DatasetForm.svelte
  client/src/lib/components/DatasetFormLayout/DatasetFormLayout.svelte
  client/src/lib/repositories/auth.ts
  client/src/routes/__error.svelte
  client/src/routes/__layout-blank.svelte
  client/src/routes/contribuer/index@blank.svelte
  client/src/routes/fiches/[id]/edit@blank.svelte
  client/src/tests/e2e/fixtures.ts
  client/src/tests/e2e/global-setup.ts
  client/tsconfig.json
Labels: front

#180 Implement tags backend + front
  client/.eslintrc.cjs
  client/src/definitions/datasets.ts
  client/src/definitions/tag.ts
  client/src/lib/components/DatasetForm/DatasetForm.spec.ts
  client/src/lib/components/DatasetForm/DatasetForm.svelte
  client/src/lib/components/SearchInput/SearchInput.spec.ts
  client/src/lib/components/SearchInput/SearchInput.svelte
  client/src/lib/components/Tag/Tag.spec.ts
  client/src/lib/components/Tag/Tag.svelte
  client/src/lib/components/TagSelector/TagSelector.spec.ts
  client/src/lib/components/TagSelector/TagSelector.svelte
  client/src/lib/repositories/tags.ts
  client/src/lib/transformers/dataset.ts
  client/src/lib/transformers/form.spec.ts
  client/src/lib/transformers/form.ts
  client/src/lib/util/object.spec.ts
  client/src/lib/util/object.ts
  client/src/routes/contribuer/index@blank.svelte
  client/src/routes/fiches/[id]/edit.svelte
  client/src/routes/fiches/[id]/edit@blank.svelte
  client/src/tests/e2e/contribuer.spec.ts
  client/src/tests/e2e/edit.spec.ts
  client/src/tests/e2e/fixtures.ts
  client/src/tests/factories/dataset.ts
  client/src/tests/factories/tags.ts
  docs/fr/outils.md
  ops/ansible/environments/demo/assets/initdata.yml
  ops/ansible/environments/staging/assets/initdata.yml
  server/api/datasets/schemas.py
  server/api/routes.py
  server/api/tags/__init__.py
  server/api/tags/routes.py
  server/application/datasets/commands.py
  server/application/datasets/handlers.py
  server/application/datasets/views.py
  server/application/tags/__init__.py
  server/application/tags/commands.py
  server/application/tags/handlers.py
  server/application/tags/queries.py
  server/application/tags/views.py
  server/config/di.py
  server/domain/datasets/entities.py
  server/domain/tags/__init__.py
  server/domain/tags/entities.py
  server/domain/tags/exceptions.py
  server/domain/tags/repositories.py
  server/infrastructure/datasets/repositories.py
  server/infrastructure/tags/__init__.py
  server/infrastructure/tags/module.py
  server/infrastructure/tags/repositories.py
  server/migrations/versions/e951f6fd7fbf_add_dataset_tags.py
  tests/api/test_datasets.py
  tests/api/test_datasets_search.py
  tests/api/test_tags.py
  tests/tools/test_initdata.py
  tools/initdata.py
  tools/initdata.yml
Labels: back

#215 Set default git_version in common group variables
  ops/ansible/environments/demo/group_vars/web.yml
  ops/ansible/environments/sandbox/group_vars/web.yml
  ops/ansible/environments/staging/group_vars/web.yml
  ops/ansible/group_vars/web.yml
Labels: infra, refactor

#230 Update testing-library
  client/package-lock.json
  client/package.json
Labels: front, dependencies

#231 Allow triggering manual CI runs
  .github/workflows/ci.yml
Labels: technical

#235 Add changepassword tool
  Makefile
  server/application/auth/commands.py
  server/application/auth/handlers.py
  server/domain/auth/entities.py
  server/domain/auth/repositories.py
  server/infrastructure/auth/module.py
  server/infrastructure/auth/repositories.py
  tests/application/__init__.py
  tests/application/test_auth.py
  tools/changepassword.py
Labels: technical, back

#229 Paginate dataset list
  client/src/constants.ts
  client/src/definitions/fetch.ts
  client/src/definitions/pagination.ts
  client/src/lib/components/Pagination/Pagination.spec.ts
  client/src/lib/components/Pagination/Pagination.svelte
  client/src/lib/repositories/datasets.ts
  client/src/lib/transformers/pagination.spec.ts
  client/src/lib/transformers/pagination.ts
  client/src/lib/util/array.spec.ts
  client/src/lib/util/array.ts
  client/src/lib/util/pagination.ts
  client/src/lib/util/urls.spec.ts
  client/src/lib/util/urls.ts
  client/src/routes/fiches/search.svelte
  client/src/routes/index.svelte
  client/src/tests/e2e/home.spec.ts
  client/src/tests/e2e/search.spec.ts
  server/api/datasets/schemas.py
  server/domain/common/pagination.py
  server/infrastructure/helpers/pydantic.py
  tests/api/test_datasets.py
  tests/unit/test_pagination.py
Labels: front

#239 Refactor DI container code
  server/config/di.py
  server/seedwork/application/di.py
  server/seedwork/application/modules.py
  tests/unit/test_di.py
Labels: technical, refactor, back

#246 Drop flaky created_at assertion
  tests/api/test_datasets.py
  tests/helpers.py
Labels: technical, back

#226 Front: etq utilisateur je peux voir le statut open data dune fiche de jeu de données
  client/src/assets/icons/dsfr-icon-extras/custom/open-data.svg
  client/src/assets/icons/dsfr-icon-extras/custom/restricted-data.svg
  client/src/lib/components/DatasetListItem/DatasetListItem.svelte
  client/src/lib/components/Pagination/Pagination.svelte
  client/src/routes/fiches/[id]/index.spec.ts
  client/src/routes/fiches/[id]/index.svelte
  client/src/routes/index.svelte
  client/src/styles/dsfr-icon-extras.css
  tools/iconfont.py
Labels: staging

#245 Add debug mode with SQL toolbar
  docs/fr/demarrage.md
  requirements.txt
  server/api/app.py
  server/api/debugging/__init__.py
  server/api/debugging/debug_toolbar/__init__.py
  server/api/debugging/debug_toolbar/panels.py
  server/config/di.py
  server/config/settings.py
  server/infrastructure/database.py
  server/migrations/env.py
  tests/conftest.py
  tests/helpers.py
  tests/test_debugging.py
Labels: technical, back

#249 Make staging-sync recreate staging branch instead of patching
  Makefile
  docs/fr/ops.md
Labels: infra, technical

#248 Upgrade to DSFR 1.5.1
  Makefile
  client/package-lock.json
  client/package.json
  client/src/app.css
  client/src/assets/icons/dsfr-icon-extras/bank-line.svg
  client/src/assets/icons/dsfr-icon-extras/heart-line.svg
  client/src/lib/components/DatasetForm/DatasetForm.svelte
  client/src/lib/components/DatasetListItem/DatasetListItem.svelte
  client/src/lib/components/Footer/Footer.svelte
  client/src/lib/components/Header/Header.svelte
  client/src/lib/components/Pagination/Pagination.spec.ts
  client/src/lib/components/Pagination/Pagination.svelte
  client/src/routes/__layout.svelte
  client/src/routes/fiches/[id]/index.svelte
  client/src/styles/dsfr-icon-extras.css
  requirements.txt
  tools/iconextras.py
  tools/iconfont.py
Labels: staging

#253 Update dataset detail subtitle to use hardcoded org name
  client/src/routes/fiches/[id]/index.svelte
Labels: staging

#256 Drop fill="none" from restricted-data icon
  client/src/assets/icons/dsfr-icon-extras/custom/restricted-data.svg
  client/src/styles/dsfr-icon-extras.css
  docs/fr/outils.md
Labels: bug, front

#260 Drop --ff-only from ops-staging
  Makefile
Labels: infra, technical

#262 Refactor dataset form menu
  client/src/lib/components/DatasetForm/DatasetForm.svelte
  client/src/lib/components/DatasetFormLayout/DatasetFormLayout.svelte
  client/src/lib/util/array.ts
  client/src/lib/util/html.ts
  client/src/tests/e2e/contribuer.spec.ts
Labels: refactor

#263 Move validators from API schemas to application layer
  server/api/app.py
  server/api/datasets/schemas.py
  server/api/errors.py
  server/application/auth/commands.py
  server/application/auth/queries.py
  server/application/datasets/commands.py
  server/domain/common/pagination.py
  tests/api/test_datasets_search.py
  tests/application/test_auth.py
  tests/helpers.py
  tests/tools/test_initdata.py
  tools/initdata.yml
Labels: refactor, back
