Repository etalab/catalogage-donnees, pull requests merged in 2022-07, with the labels that each got.

#323 Fix OpenAPI docs security scheme binding
  server/api/app.py
  server/api/auth/backends/token.py
  server/api/auth/dependencies.py
  tests/test_app.py
Labels: bug, docs, technical, back

#326 refacto: implement pagination for search page
  client/src/routes/fiches/_PaginationContainer.svelte
  client/src/routes/fiches/search.svelte
  client/src/routes/index.svelte
Labels: front

#328 refacto: extract perform search function in search.spec.ts
  client/src/tests/e2e/search.spec.ts
Labels: refactor, front

#327 fix: click outside behavior in SearchableSelect
  client/src/lib/components/SearchableSelect/SearchableSelect.spec.ts
  client/src/lib/components/SearchableSelect/SearchableSelect.svelte
  client/src/lib/util/format.ts
Labels: front

#330 Bump svelte to ^3.48.0 and prettier-svelte-plugin to ^2.7.0
  client/package-lock.json
  client/package.json
Labels: technical, front, dependencies

#329 Extract reusable InputField
  client/src/lib/components/DatasetForm/DatasetForm.svelte
  client/src/lib/components/InputField/InputField.svelte
  client/src/lib/components/TextareaField/TextareaField.svelte
Labels: refactor

#332 Fix search page pagination
  client/src/lib/util/pagination.spec.ts
  client/src/lib/util/pagination.ts
  client/src/routes/fiches/_PaginationContainer.svelte
  client/src/routes/fiches/search.svelte
  client/src/routes/index.svelte
  client/src/tests/e2e/search.spec.ts
Labels: bug, front

#337 Add license field to API
  client/src/lib/transformers/dataset.ts
  server/api/datasets/routes.py
  server/api/datasets/schemas.py
  server/api/licenses/__init__.py
  server/api/licenses/routes.py
  server/api/routes.py
  server/application/datasets/commands.py
  server/application/datasets/handlers.py
  server/application/datasets/views.py
  server/application/licenses/__init__.py
  server/application/licenses/handlers.py
  server/application/licenses/queries.py
  server/config/di.py
  server/domain/datasets/entities.py
  server/domain/datasets/repositories.py
  server/domain/datasets/specifications.py
  server/domain/licenses/__init__.py
  server/domain/licenses/entities.py
  server/infrastructure/datasets/models.py
  server/infrastructure/datasets/queries/get_all.py
  server/infrastructure/datasets/repositories.py
  server/infrastructure/licenses/__init__.py
  server/infrastructure/licenses/module.py
  server/migrations/versions/1cd8f59f2f0f_add_dataset_license.py
  server/seedwork/application/modules.py
  tests/api/test_datasets.py
  tests/api/test_datasets_filters.py
  tests/api/test_licenses.py
  tests/factories.py
  tools/initdata.yml
Labels: back

#333 Allow distinguishing when DatasetForm is created without initial values
  client/src/lib/components/DatasetForm/DatasetForm.svelte
Labels: refactor, front

#311 Add license field
  client/src/definitions/datasetFilters.ts
  client/src/definitions/datasets.ts
  client/src/lib/components/DatasetForm/DatasetForm.spec.ts
  client/src/lib/components/DatasetForm/DatasetForm.svelte
  client/src/lib/components/DatasetForm/_LicenseField.spec.ts
  client/src/lib/components/DatasetForm/_LicenseField.svelte
  client/src/lib/components/DatasetListItem/DatasetListItem.svelte
  client/src/lib/repositories/licenses.ts
  client/src/lib/transformers/dataset.ts
  client/src/lib/transformers/datasetFilters.spec.ts
  client/src/lib/transformers/datasetFilters.ts
  client/src/lib/util/string.spec.ts
  client/src/lib/util/string.ts
  client/src/routes/contribuer/index@blank.svelte
  client/src/routes/fiches/[id]/_AsideItem.svelte
  client/src/routes/fiches/[id]/edit@blank.svelte
  client/src/routes/fiches/[id]/index.spec.ts
  client/src/routes/fiches/[id]/index.svelte
  client/src/routes/fiches/_FilterPanel.svelte
  client/src/tests/e2e/contribuer.spec.ts
  client/src/tests/e2e/search.spec.ts
  client/src/tests/factories/dataset.ts
Labels: front, staging

#348 Rework permission composition
  server/api/auth/dependencies.py
  server/api/auth/permissions.py
  server/api/auth/routes.py
  server/api/datasets/filters/routes.py
  server/api/datasets/routes.py
  server/api/licenses/routes.py
  server/api/tags/routes.py
  tests/unit/test_permissions.py
Labels: refactor, back

#354 Run CI on any PR branch
  .github/workflows/ci.yml
Labels: technical

#351 Add catalog and legacy organization
  server/application/auth/commands.py
  server/application/auth/handlers.py
  server/application/auth/views.py
  server/application/catalog_records/views.py
  server/application/datasets/commands.py
  server/application/datasets/handlers.py
  server/config/di.py
  server/domain/auth/entities.py
  server/domain/catalog_records/entities.py
  server/domain/catalogs/__init__.py
  server/domain/catalogs/entities.py
  server/domain/organizations/entities.py
  server/infrastructure/auth/repositories.py
  server/infrastructure/catalog_records/repositories.py
  server/infrastructure/catalogs/__init__.py
  server/infrastructure/catalogs/models.py
  server/infrastructure/catalogs/module.py
  server/infrastructure/organizations/models.py
  server/migrations/versions/4e40358ad25c_add_catalog.py
  server/migrations/versions/f2ef4eef61e3_create_legacy_organization.py
  tests/api/test_auth.py
  tests/api/test_datasets.py
  tests/factories.py
  tests/infrastructure/test_catalogs.py
Labels: back, staging
