Repository etalab/catalogage-donnees, pull requests merged in 2022-04, with the labels that each got.

#155 Show migrate task as changed only if migrations effectively applied
  ops/ansible/roles/web/tasks/db.yml
Labels: infra, technical

#154 doc: improve readme and create a troubleshooting point
  docs/fr/demarrage.md
Labels: documentation

#158 Add tests for initdata tool
  tests/tools/__init__.py
  tests/tools/test_initdata.py
  tools/initdata.py
  tools/initdata.yml
Labels: technical

#163 Address several eslint warnings
  client/src/env.ts
  client/src/lib/components/DatasetForm/DatasetForm.svelte
  client/src/lib/fetch.ts
  client/src/lib/stores/auth/index.ts
  client/src/lib/stores/localStorage/index.ts
  client/src/lib/util/format.ts
  client/src/lib/util/paths.ts
  client/src/lib/util/urls.ts
  client/src/tests/e2e/contribuer.spec.ts
  client/src/tests/e2e/details.spec.ts
  client/src/tests/e2e/edit.spec.ts
  client/src/tests/e2e/global-setup.ts
  client/src/tests/e2e/home.spec.ts
  client/src/tests/e2e/login.spec.ts
  client/src/tests/e2e/search.spec.ts
  client/svelte.config.js
Labels: refactor, front

#174 Update ops install docs
  docs/fr/ops.md
Labels: documentation, infra

#157 Add dataset update fields + service field
  client/src/constants.ts
  client/src/definitions/datasets.d.ts
  client/src/lib/components/ContactEmailsField/ContactEmailsField.spec.ts
  client/src/lib/components/ContactEmailsField/ContactEmailsField.svelte
  client/src/lib/components/DatasetForm/DatasetForm.spec.ts
  client/src/lib/components/DatasetForm/DatasetForm.svelte
  client/src/lib/components/DatasetList/DatasetList.spec.ts
  client/src/lib/components/DatasetListItem/DatasetListItem.spec.ts
  client/src/lib/repositories/datasets.ts
  client/src/lib/transformers/dataset.spec.ts
  client/src/lib/transformers/dataset.ts
  client/src/lib/util/format.ts
  client/src/routes/fiches/[id]/index.spec.ts
  client/src/tests/e2e/contribuer.spec.ts
  client/src/tests/e2e/fixtures.ts
  client/src/tests/factories/dataset.ts
  server/api/datasets/schemas.py
  server/application/datasets/commands.py
  server/domain/datasets/entities.py
  server/infrastructure/datasets/repositories.py
  server/migrations/versions/6fd05f9d4158_add_dataset_service_update_frequency_last_updated_at.py
  tests/api/test_datasets.py
  tests/api/test_datasets_search.py
  tools/initdata.yml
Labels: front, back

#175 Document how to deploy from a specific git ref
  docs/fr/ops.md
Labels: documentation, infra

#171 Allow admins to delete datasets
  .github/workflows/ci.yml
  client/package.json
  client/playwright.config.ts
  client/src/lib/fetch.ts
  client/src/lib/repositories/datasets.ts
  client/src/lib/stores/auth/index.ts
  client/src/playwright.config.ts
  client/src/routes/fiches/[id]/edit.svelte
  client/src/routes/fiches/[id]/index.svelte
  client/src/tests/app.navigation.mock.ts
  client/src/tests/e2e/constants.ts
  client/src/tests/e2e/edit.spec.ts
  client/src/tests/e2e/fixtures.ts
  client/src/tests/e2e/global-setup.ts
  client/vitest.config.ts
  server/api/datasets/routes.py
  tests/api/test_datasets.py
Labels: front, back

#182 refacto: move fields to fit with the new layout
  client/src/lib/components/DatasetForm/DatasetForm.spec.ts
  client/src/lib/components/DatasetForm/DatasetForm.svelte
Labels: front

#177 feat:125 - add geographical coverage field
  client/src/constants.ts
  client/src/definitions/datasets.ts
  client/src/definitions/form.ts
  client/src/lib/components/DatasetForm/DatasetForm.spec.ts
  client/src/lib/components/DatasetForm/DatasetForm.svelte
  client/src/lib/components/Select/Select.spec.ts
  client/src/lib/components/Select/Select.svelte
  client/src/lib/transformers/dataset.ts
  client/src/lib/transformers/form.spec.ts
  client/src/lib/transformers/form.ts
  client/src/lib/util/form.ts
  client/src/tests/e2e/contribuer.spec.ts
  client/src/tests/e2e/fixtures.ts
  client/src/tests/factories/dataset.ts
Labels: front

#178 Add geographical_coverage and technical_source to API + form fields in the UI
  client/src/constants.ts
  client/src/definitions/datasets.ts
  client/src/definitions/form.ts
  client/src/lib/components/DatasetForm/DatasetForm.spec.ts
  client/src/lib/components/DatasetForm/DatasetForm.svelte
  client/src/lib/components/Select/Select.spec.ts
  client/src/lib/components/Select/Select.svelte
  client/src/lib/transformers/dataset.ts
  client/src/lib/transformers/form.spec.ts
  client/src/lib/transformers/form.ts
  client/src/lib/util/form.ts
  client/src/tests/e2e/contribuer.spec.ts
  client/src/tests/e2e/fixtures.ts
  client/src/tests/factories/dataset.ts
  server/api/datasets/schemas.py
  server/application/datasets/commands.py
  server/application/datasets/views.py
  server/domain/datasets/entities.py
  server/infrastructure/datasets/repositories.py
  server/migrations/versions/f92d0ee57d88_add_dataset_geographical_coverage_.py
  tests/api/test_datasets.py
  tests/api/test_datasets_search.py
  tools/initdata.yml
Labels: front, back

#192 Various UI adjustments
  client/src/lib/components/DatasetForm/DatasetForm.spec.ts
  client/src/lib/components/DatasetForm/DatasetForm.svelte
  client/src/lib/components/DatasetListItem/DatasetListItem.svelte
  client/src/lib/components/Footer/Footer.svelte
  client/src/lib/components/Header/Header.svelte
  client/src/lib/util/format.spec.ts
  client/src/lib/util/format.ts
  client/src/routes/__layout.svelte
  client/src/routes/fiches/[id]/edit.svelte
  client/src/routes/fiches/[id]/index.spec.ts
  client/src/routes/fiches/[id]/index.svelte
  client/src/routes/index.svelte
  client/src/routes/login.svelte
  client/src/tests/e2e/contribuer.spec.ts
  client/src/tests/e2e/details.spec.ts
  client/src/tests/e2e/home.spec.ts
Labels: front

#189 Move dataset.created_at to new catalog_record sub-entity
  client/src/definitions/catalog_records.ts
  client/src/definitions/datasets.ts
  client/src/lib/components/DatasetListItem/DatasetListItem.spec.ts
  client/src/lib/components/DatasetListItem/DatasetListItem.svelte
  client/src/lib/transformers/dataset.spec.ts
  client/src/lib/transformers/dataset.ts
  client/src/routes/fiches/[id]/index.spec.ts
  client/src/tests/factories/dataset.ts
  server/application/catalog_records/__init__.py
  server/application/catalog_records/views.py
  server/application/datasets/handlers.py
  server/application/datasets/views.py
  server/config/di.py
  server/domain/catalog_records/__init__.py
  server/domain/catalog_records/entities.py
  server/domain/catalog_records/repositories.py
  server/domain/datasets/entities.py
  server/infrastructure/catalog_records/__init__.py
  server/infrastructure/catalog_records/repositories.py
  server/infrastructure/datasets/repositories.py
  server/migrations/versions/012e4606ddc1_add_catalog_record.py
  tests/api/test_datasets.py
  tests/conftest.py
Labels: refactor

#198 Bump backend deps
  requirements.txt
  setup.cfg
  tests/conftest.py
Labels: technical, back

#200 Generalize passing passwords from env in initdata
  .env.example
  .github/workflows/ci.yml
  client/src/playwright.config.ts
  docs/fr/demarrage.md
  docs/fr/outils.md
  ops/ansible/roles/web/templates/.env.j2
  tests/tools/test_initdata.py
  tools/initdata.py
  tools/initdata.yml
Labels: refactor, back
